---
- name: Ensure Python is installed
  ansible.builtin.yum:
    name: "{{ py_pkg }}"
    state: present


- name: Create the virtual environment if it doesn't exist
  ansible.builtin.command:
    cmd: "{{ py_cmd }} -m venv {{ venv_directory }}"
  args:
    creates: "{{ venv_directory }}/bin/activate"


- name: Ensure perms for virtual environment directory
  ansible.builtin.file:
    path: "{{ venv_directory }}"
    state: directory
    owner: "{{ venv_owner }}"
    group: "{{ venv_group }}"
    recurse: yes
    mode: '0755'


- name: Ensure latest pip
  ansible.builtin.pip:
    name: pip
    virtualenv: "{{ venv_directory }}"
    state: latest
