---
- name: Ensure Python is installed
  ansible.builtin.yum:
    name: "{{ py_pkg }}"
    state: present

- name: Create directory for virtual environment
  ansible.builtin.file:
    path: "{{ venv_directory }}"
    state: directory
    owner: "{{ venv_owner }}"
    group: "{{ venv_group }}"
    mode: '0755'

- name: Create the virtual environment if it doesn't exist
  ansible.builtin.command:
    cmd: "{{ py_cmd }} -m venv {{ venv_directory }}"
  args:
    creates: "{{ venv_directory }}/bin/activate"

- name: Ensure the virtual environment exist
  ansible.builtin.debug:
    msg: "Python virtual environment has been successfully created."

- name: Activate the virtual environment and display Python version
  ansible.builtin.shell: |
    source "{{ venv_directory }}/bin/activate"
    python --version
  args:
    executable: /bin/bash
