---
# tasks file for poetry_tool

- name: pip install poetry
  ansible.builtin.pip:
    virtualenv: "{{ virtenv_path }}"
    name: poetry
    state: latest

- name: symlink poetry
  ansible.builtin.file:
    src: "{{ virtenv_path }}/bin/poetry"
    dest: /usr/local/bin/poetry
    state: link
