---
# tasks file for igtfcerts/

- name: Add EGI trustanchors cert repository file
  ansible.builtin.yum_repository:
    name: EGI-trustanchors
    description: EPEL YUM repo
    file: egi-trustanchors
    baseurl: http://repository.egi.eu/sw/production/cas/1/current/
    gpgcakey: http://repository.egi.eu/sw/production/cas/1/GPG-KEY-EUGridPMA-RPM-3
    gpgcheck: true
    enabled: true
