---

- name: Import EGI GPG key
  ansible.builtin.rpm_key:
    state: present
    key: "{{ igtfcerts_repo_key }}"


- name: Add EGI trustanchors cert repository file
  ansible.builtin.yum_repository:
    name: EGI-trustanchors
    description: Repository with IGTF CA certificates
    file: egi-trustanchors
    baseurl: "{{ igtfcerts_baseurl }}"
    gpgcakey: "{{ igtfcerts_repo_key }}"
    gpgcheck: true
    enabled: true


- name: Install ca-policy-egi-core RPM
  ansible.builtin.dnf:
    name: "{{ igtfcerts_pkg_name }}"
    state: present
  notify: Update CA bundle
