---
- name: Play to test for hosts file in directory output
  hosts: localhost
  tasks:
    - name: Gather directory listing from local system
      ansible.builtin.shell: "cat /etc/hosts"
      register: shellresult

    - name: Alert if we find a hosts file
      ansible.builtin.debug:
        msg: "Found localhost file!"
      when: '"localhost" in shellresult.stdout'

- name: Time for looping
  hosts: localhost
  tasks:
    - name: Basic loop example
      ansible.builtin.command: echo "{{ item }}"
      loop:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
      when: item|int > 3

- name: Loop user create
  hosts: debian1
  become: yes
  tasks:
    - name: Loop to create users
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
        groups: "users"
      loop:
        - "testuser1"
        - "testuser2"

- name: Loop user create from global var
  hosts: debian1
  become: yes
  tasks:
    - name: Loop to create needed groups from flow collection
      ansible.builtin.group:
        name: "{{ item.group}}"
        state: present
      loop: "{{ debian_users }}"

    - name: Loop to create needed groups from regular dictionary collection
      ansible.builtin.group:
        name: "{{ item.group}}"
        state: present
      loop: "{{ debian_users2 }}"

    - name: Loop to create users from flow collection
      ansible.builtin.user:
        name: "{{ item.name }}"
        state: present
        group: "{{ item.group }}"
        append: false
      loop: "{{ debian_users }}"

    - name: Loop to create users from regular dictionary collection
      ansible.builtin.user:
        name: "{{ item.name }}"
        state: present
        group: "{{ item.group }}"
        append: false
      loop: "{{ debian_users2 }}"

- name: Various loop examples deciphered with debug
  hosts: debian1
  tasks:
    - name: Loop echo variables
      ansible.builtin.debug:
        var: item
      loop:
        - 1
        - 2
        - 3

    - name: Using dict2items
      ansible.builtin.debug:
        msg: "{{ item.key }} - {{ item.value }}"
      loop: "{{ tag_data | dict2items }}"
      vars:
        tag_data:
          Environment: dev
          Application: payment
