---
- name: Play to test for hosts file in directory output
  hosts: localhost
  tasks:
    - name: Gather directory listing from local system
      ansible.builtin.shell: "cat /etc/hosts"
      register: shellresult

    - name: Alert if we find a hosts file
      ansible.builtin.debug:
        msg: "Found localhost file!"
      when: '"localhost" in shellresult.stdout'

- name: Time for looping
  hosts: localhost
  vars:
    mylist: [0, 2, 4, 5, 8, 10]
    mylist2: [10, 22, 44, 55, 88, 101]
  tasks:
    - name: Basic loop example
      ansible.builtin.command: echo "{{ item }}"
      loop:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
      when: item|int > 3
    - name: Run with items greater than 5
      ansible.builtin.command: echo "{{ item }}"
      loop: "{{ mylist }}"
      when: item > 5
    - name: Run with items greater than 5 - skip undefined list
      ansible.builtin.command: echo "{{ item }}"
      loop: "{{ no_mylist|default([]) }}"
      when: item > 5
    - name: Run with items greater than 5 - skip undefined dict
      ansible.builtin.command: echo "{{ item.key }}"
      loop: "{{ query('dict', mydict|default({})) }}"
      when: item.value > 5

- name: Loop user create
  hosts: debian1
  become: yes
  tasks:
    - name: Loop to create users
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
        groups: "users"
      loop:
        - "testuser1"
        - "testuser2"

- name: Loop user create from global var
  hosts: debian1
  become: yes
  tasks:
    - name: Loop to create needed groups from flow collection
      ansible.builtin.group:
        name: "{{ item.group}}"
        state: present
      loop: "{{ debian_users }}"

    - name: Loop to create needed groups from regular dictionary collection
      ansible.builtin.group:
        name: "{{ item.group}}"
        state: present
      loop: "{{ debian_users2 }}"

    - name: Loop to create users from flow collection
      ansible.builtin.user:
        name: "{{ item.name }}"
        state: present
        group: "{{ item.group }}"
        append: false
      loop: "{{ debian_users }}"

    - name: Loop to create users from regular dictionary collection
      ansible.builtin.user:
        name: "{{ item.name }}"
        state: present
        group: "{{ item.group }}"
        append: false
      loop: "{{ debian_users2 }}"

- name: Various loop examples deciphered with debug
  hosts: debian1
  tasks:
    - name: Loop echo variables
      ansible.builtin.debug:
        var: item
      loop:
        - 1
        - 2
        - 3

    - name: Using dict2items
      ansible.builtin.debug:
        msg: "{{ item.key }} - {{ item.value }}"
      loop: "{{ tag_data | dict2items }}"
      vars:
        tag_data:
          Environment: dev
          Application: payment

- name: Register variable play
  hosts: debian1
  tasks:
  - name: retrieve list
    ansible.builtin.command: ls /home
    register: home_dirs

  - name: debug list
    ansible.builtin.debug:
      var: home_dirs

- name: Import and include task
  hosts: debian1
  tasks:
    - import_tasks: imported_tasks.yml
      when: x is not defined
