---
- name: Play to test for hosts file in directory output
  hosts: localhost
  tasks:
    - name: Gather directory listing from local system
      ansible.builtin.shell: "cat /etc/hosts"
      register: shellresult

    - name: Alert if we find a hosts file
      ansible.builtin.debug:
        msg: "Found localhost file!"
      when: '"localhost" in shellresult.stdout'

    - name: Echo a value from the loop
      ansible.builtin.command: echo "{{ item }}"
      loop:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
      when: item|int > 3
