---
- name: Playbook to configure connectors machines
  hosts: connectors
  become: true
  roles:
    - role: chezmoi_dotfiles
    - role: igtfcerts_cabundle
    - role: poetry_tool
    - role: python_venv
      vars:
        venv_directory: /opt/argo-connectors


- name: Install argo-connectors
  hosts: connectors
  become: true
  tasks:
    - name: pip install git+https://argo-connectors
      ansible.builtin.pip:
        virtualenv: /opt/argo-connectors
        name: git+https://github.com/ARGOeu/argo-connectors@devel#egg=argo-connectors

# vim: ft=yaml.ansible
