---
- name: Playbook to configure connectors machines
  hosts: connectors
  become: true
  roles:
    - role: chezmoi_dotfiles
    - role: python_venv
      vars:
        venv_directory: /opt/argo-connectors
    - role: igtfcerts_cabundle



# vim: ft=yaml.ansible
