---
- name: My first Ansible Playbook
  hosts: all
  become: yes
  tasks:
    - name: Install Apache2
      ansible.builtin.dnf:
        name:
          - httpd
          - mod_ssl
        state: latest
