---
- name: Jinja2 filtering
  hosts: localhost
  vars:
    tags:
      - key: job
        value: developer
      - key: language
        value: java
    hosts_content: "{{ lookup('file', '/etc/hosts') }}"
  tasks:
    - name: Filter the tags variable through items2dict
      ansible.builtin.debug:
        msg: '{{ tags | items2dict }}'
    - name: Load values from file
      ansible.builtin.debug:
        msg: 'file content {{ hosts_content }}'
