---

- name: Configure RPM distros
  hosts: rpms
  vars_files:
    - secret.yml
  become: yes

  tasks:
    - name: Install Apache2
      ansible.builtin.dnf:
        name:
          - httpd
          - mod_ssl
        state: latest

    - name: Print secret
      ansible.builtin.debug:
        msg: "{{ foobar }}"
