---
- name: Spawn Python virtenv using a role and prepare for chezmoi sync
  hosts: rocky1
  become: true
  roles:
    - role: python-venv
    - role: python-venv
      vars:
        venv_directory: /opt/argo-connectors/
    - role: python-venv
      vars:
        venv_directory: /opt/poem/
    - role: chezmoi-dotfiles


- name: Chezmoi init on debian
  hosts: debian1
  become: false
  roles:
    - role: chezmoi-dotfiles
