---
- name: Spawn Python virtenv using a role
  hosts: rocky1
  become: true

  roles:
    - role: python_venv
    - role: python_venv
      vars:
        venv_directory: /opt/argo-connectors/
    - role: python_venv
      vars:
        venv_directory: /opt/poem/
