services:
  ubuntu-c:
    env_file:
      - compose.env
    image: ${IMAGEC}
    command: sudo /usr/bin/supervisord -nc /etc/supervisor/supervisord.conf
    entrypoint: /sbin/init
    container_name: ubuntuc
    privileged: true
    hostname: ubuntuc
    cgroup: host
    tty: true
    tmpfs:
      - /run
      - /tmp
    stdin_open: true
    user: root
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - $HOME:/mnt
      - $HOME/.docker_zsh_history:/home/user/.zsh_history
      - /dev/log:/dev/log
      - /etc/localtime:/etc/localtime:ro
      - ../:/home/user/ansible-playground-source/
      - type: bind
        source: ${SSH_AUTH_SOCK}
        target: ${SSH_AUTH_SOCK}
    environment:
      - SSH_AUTH_SOCK

    networks:
      vrdel-ansible-play:
        ipv4_address: 172.21.0.12

  #rocky1:
    #env_file:
      #- compose.env
    #image: ${IMAGES1}
    #command: sudo /usr/bin/supervisord -nc /etc/supervisord.conf
    #entrypoint: /sbin/init
    #container_name: rocky1
    #hostname: rocky1
    #cgroup: host
    #tty: true
    #tmpfs:
      #- /run
      #- /tmp
    #stdin_open: true
    #user: root
    #volumes:
      #- /sys/fs/cgroup:/sys/fs/cgroup
      #- $HOME:/mnt
      #- $HOME/.docker_zsh_history:/home/user/.zsh_history
      #- /dev/log:/dev/log
      #- /etc/localtime:/etc/localtime:ro
      #- type: bind
        #source: ${SSH_AUTH_SOCK}
        #target: ${SSH_AUTH_SOCK}
    #environment:
      #- SSH_AUTH_SOCK
    #networks:
      #vrdel-ansible-play:
        #ipv4_address: 172.21.0.13

  #debian1:
    #env_file:
      #- compose.env
    #image: ${IMAGES2}
    #command: sudo /usr/bin/supervisord -nc /etc/supervisord.conf
    #entrypoint: /sbin/init
    #container_name: debian1
    #privileged: true
    #hostname: debian1
    #cgroup: host
    #tty: true
    #tmpfs:
      #- /run
      #- /tmp
    #stdin_open: true
    #user: root
    #volumes:
      #- /sys/fs/cgroup:/sys/fs/cgroup
      #- $HOME:/mnt
      #- $HOME/.docker_zsh_history:/home/user/.zsh_history
      #- /dev/log:/dev/log
      #- /etc/localtime:/etc/localtime:ro
      #- type: bind
        #source: ${SSH_AUTH_SOCK}
        #target: ${SSH_AUTH_SOCK}
    #environment:
      #- SSH_AUTH_SOCK
    #networks:
      #vrdel-ansible-play:
        #ipv4_address: 172.21.0.14

  #connectors:
    #env_file:
      #- compose.env
    #image: ${IMAGES3}
    #command: sudo /usr/bin/supervisord -nc /etc/supervisord.conf
    #entrypoint: /sbin/init
    #container_name: connectors
    #hostname: connectors
    #cgroup: host
    #tty: true
    #tmpfs:
      #- /run
      #- /tmp
    #stdin_open: true
    #user: root
    #volumes:
      #- /sys/fs/cgroup:/sys/fs/cgroup
      #- $HOME:/mnt
      #- $HOME/.docker_zsh_history:/home/user/.zsh_history
      #- /dev/log:/dev/log
      #- /etc/localtime:/etc/localtime:ro
      #- type: bind
        #source: ${SSH_AUTH_SOCK}
        #target: ${SSH_AUTH_SOCK}
    #environment:
      #- SSH_AUTH_SOCK
    #networks:
      #vrdel-ansible-play:
        #ipv4_address: 172.21.0.15

  #poem:
    #env_file:
      #- compose.env
    #image: ${IMAGES4}
    #command: sudo /usr/bin/supervisord -nc /etc/supervisord.conf
    #entrypoint: /sbin/init
    #container_name: poem
    #hostname: poem
    #cgroup: host
    #tty: true
    #tmpfs:
      #- /run
      #- /tmp
    #stdin_open: true
    #user: root
    #volumes:
      #- /sys/fs/cgroup:/sys/fs/cgroup
      #- $HOME:/mnt
      #- $HOME/.docker_zsh_history:/home/user/.zsh_history
      #- /dev/log:/dev/log
      #- /etc/localtime:/etc/localtime:ro
      #- type: bind
        #source: ${SSH_AUTH_SOCK}
        #target: ${SSH_AUTH_SOCK}
    #environment:
      #- SSH_AUTH_SOCK
    #networks:
      #vrdel-ansible-play:
        #ipv4_address: 172.21.0.16

  #computing:
    #env_file:
      #- compose.env
    #image: ${IMAGES5}
    #command: sudo /usr/bin/supervisord -nc /etc/supervisord.conf
    #entrypoint: /sbin/init
    #container_name: computing
    #hostname: computing
    #cgroup: host
    #tty: true
    #tmpfs:
      #- /run
      #- /tmp
    #stdin_open: true
    #user: root
    #volumes:
      #- /sys/fs/cgroup:/sys/fs/cgroup
      #- $HOME:/mnt
      #- $HOME/.docker_zsh_history:/home/user/.zsh_history
      #- /dev/log:/dev/log
      #- /etc/localtime:/etc/localtime:ro
      #- type: bind
        #source: ${SSH_AUTH_SOCK}
        #target: ${SSH_AUTH_SOCK}
    #environment:
      #- SSH_AUTH_SOCK
    #networks:
      #vrdel-ansible-play:
        #ipv4_address: 172.21.0.16

  #archiver:
    #env_file:
      #- compose.env
    #image: ${IMAGES6}
    #command: sudo /usr/bin/supervisord -nc /etc/supervisord.conf
    #entrypoint: /sbin/init
    #container_name: archiver
    #hostname: archiver
    #cgroup: host
    #tty: true
    #tmpfs:
      #- /run
      #- /tmp
    #stdin_open: true
    #user: root
    #volumes:
      #- /sys/fs/cgroup:/sys/fs/cgroup
      #- $HOME:/mnt
      #- $HOME/.docker_zsh_history:/home/user/.zsh_history
      #- /dev/log:/dev/log
      #- /etc/localtime:/etc/localtime:ro
      #- type: bind
        #source: ${SSH_AUTH_SOCK}
        #target: ${SSH_AUTH_SOCK}
    #environment:
      #- SSH_AUTH_SOCK
    #networks:
      #vrdel-ansible-play:
        #ipv4_address: 172.21.0.17

  #rocky2:
    #env_file:
      #- compose.env
    #image: ${IMAGES7}
    #command: sudo /usr/bin/supervisord -nc /etc/supervisord.conf
    #entrypoint: /sbin/init
    #container_name: rocky2
    #hostname: rocky2
    #cgroup: host
    #tty: true
    #tmpfs:
      #- /run
      #- /tmp
    #stdin_open: true
    #user: root
    #volumes:
      #- /sys/fs/cgroup:/sys/fs/cgroup
      #- $HOME:/mnt
      #- $HOME/.docker_zsh_history:/home/user/.zsh_history
      #- /dev/log:/dev/log
      #- /etc/localtime:/etc/localtime:ro
      #- type: bind
        #source: ${SSH_AUTH_SOCK}
        #target: ${SSH_AUTH_SOCK}
    #environment:
      #- SSH_AUTH_SOCK
    #networks:
      #vrdel-ansible-play:
        #ipv4_address: 172.21.0.17
  #rocky3:
    #env_file:
      #- compose.env
    #image: ${IMAGES7}
    #command: sudo /usr/bin/supervisord -nc /etc/supervisord.conf
    #entrypoint: /sbin/init
    #container_name: rocky3
    #hostname: rocky3
    #cgroup: host
    #tty: true
    #tmpfs:
      #- /run
      #- /tmp
    #stdin_open: true
    #user: root
    #volumes:
      #- /sys/fs/cgroup:/sys/fs/cgroup
      #- $HOME:/mnt
      #- $HOME/.docker_zsh_history:/home/user/.zsh_history
      #- /dev/log:/dev/log
      #- /etc/localtime:/etc/localtime:ro
      #- type: bind
        #source: ${SSH_AUTH_SOCK}
        #target: ${SSH_AUTH_SOCK}
    #environment:
      #- SSH_AUTH_SOCK
    #networks:
      #vrdel-ansible-play:
        #ipv4_address: 172.21.0.18
  ubuntu2:
    env_file:
      - compose.env
    image: ${IMAGES9}
    command: sudo /usr/bin/supervisord -nc /etc/supervisord.conf
    entrypoint: /sbin/init
    container_name: ubuntu2
    hostname: ubuntu2
    privileged: true
    cgroup: host
    tty: true
    tmpfs:
      - /run
      - /tmp
    stdin_open: true
    user: root
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - $HOME:/mnt
      - $HOME/.docker_zsh_history:/home/user/.zsh_history
      - /dev/log:/dev/log
      - /etc/localtime:/etc/localtime:ro
      - type: bind
        source: ${SSH_AUTH_SOCK}
        target: ${SSH_AUTH_SOCK}
    environment:
      - SSH_AUTH_SOCK
    networks:
      vrdel-ansible-play:
        ipv4_address: 172.21.0.19

networks:
  vrdel-ansible-play:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24
          gateway: 172.21.0.1
