---
- name: Chezmoi init
  ansible.builtin.shell:
    cmd: curl -sfL https://git.io/chezmoi | sh
  args:
    creates: /home/{{ chezmoi_user }}/bin/chezmoi

- name: Copy chezmoi-apply-config.sh
  ansible.builtin.template:
    src: chezmoi-config-apply.sh.j2
    dest: /home/{{ chezmoi_user }}/chezmoi-config-apply.sh
    mode: '0755'
