---

- name: Check if {{ item }}{{ igtfcerts_backup_appendix }} exists
  listen: Update CA bundle
  ansible.builtin.stat:
    path: "{{ item }}{{ igtfcerts_backup_appendix }}"
  register:
    saved_stat

- name: Save original CA bundle - {{ item }}
  listen: Update CA bundle
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ item }}{{ igtfcerts_backup_appendix }}"
    remote_src: yes
  when: not saved_stat.stat.exists
