---

- name: Ensure clean anchors - delete everything under
  listen: Update CA bundle
  ansible.builtin.file:
    path: "{{ igtfcerts_anchor_path }}"
    state: absent

- name: Ensure clean anchors - recreate empty anchors/ directory
  listen: Update CA bundle
  ansible.builtin.file:
    path: "{{ igtfcerts_anchor_path }}"
    state: directory

