---

# add handlers

- name: Check if /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem.saved.igtfcerts-role exists
  listen: Update CA bundle
  ansible.builtin.stat:
    path: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem.saved.igtfcers-role
  register:
    saved_stat

- name: Save original CA bundle - tls-ca-bundle.pem
  listen: Update CA bundle
  ansible.builtin.copy:
    src: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
    dest: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem.saved.igtfcerts-role
    remote_src: yes
  when: not saved_stat.stat.exists

- name: Check if /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt.saved.igtfcerts-role exists
  listen: Update CA bundle
  ansible.builtin.stat:
    path: /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt.saved.igtfcerts-role
  register:
    saved_stat2

- name: Save original CA bundle - ca-bundle.trust.crt
  listen: Update CA bundle
  ansible.builtin.copy:
    src: /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt
    dest: /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt.saved.igtfcerts-role
    remote_src: yes
  when: not saved_stat2.stat.exists

- name: Ensure clean anchors - delete everything under
  listen: Update CA bundle
  ansible.builtin.file:
    path: /etc/pki/ca-trust/source/anchors/
    state: absent

- name: Ensure clean anchors - recreate empty anchors/ directory
  listen: Update CA bundle
  ansible.builtin.file:
    path: /etc/pki/ca-trust/source/anchors/
    state: directory

- name: "List all target IGTF target *.pem files"
  listen: Update CA bundle
  ansible.builtin.find:
    paths: /etc/grid-security/certificates/
    patterns: '*.pem'
  register: target_pems

- name: Copy IGTF CA's as anchors
  listen: Update CA bundle
  ansible.builtin.copy:
    src: "{{ item.path }}"
    dest: /etc/pki/ca-trust/source/anchors/
    remote_src: yes
  loop: "{{ target_pems.files }}"
  loop_control:
    label: "{{ item.path }}"

- name: Update bundle
  listen: Update CA bundle
  ansible.builtin.command:
    cmd: update-ca-trust


# clean handlers

- name: Ensure clean anchors - delete everything under
  listen: Reset CA bundle
  ansible.builtin.file:
    path: /etc/pki/ca-trust/source/anchors/
    state: absent

- name: Ensure clean anchors - recreate empty anchors/ directory
  listen: Reset CA bundle
  ansible.builtin.file:
    path: /etc/pki/ca-trust/source/anchors/
    state: directory

- name: Revert back original CA bundle - tls-ca-bundle.pem
  listen: Reset CA bundle
  ansible.builtin.copy:
    src: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem.saved.igtfcerts-role
    dest: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
    remote_src: yes
    force: true
  ignore_errors: true

- name: Delete /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem.saved.igtfcerts-role
  listen: Reset CA bundle
  ansible.builtin.file:
    path: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem.saved.igtfcerts-role
    state: absent
  ignore_errors: true

- name: Revert back original CA bundle - ca-bundle.trust.crt
  listen: Reset CA bundle
  ansible.builtin.copy:
    src: /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt.saved.igtfcerts-role
    dest: /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt
    remote_src: yes
    force: true
  ignore_errors: true

- name: Delete /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt.saved.igtfcerts-role
  listen: Reset CA bundle
  ansible.builtin.file:
    src: /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt.saved.igtfcerts-role
    state: absent
  ignore_errors: true
