---

# add handlers
- name: Backup CA bundle
  listen: Update CA bundle
  include_tasks: ./backup_bundle.yml
  loop: "{{ target_cabundles }}"

- name: Clean anchors/
  listen: Update CA bundle
  include_tasks: ./clean_anchors.yml

- name: Update CA bundle
  listen: Update CA bundle
  include_tasks: ./update_bundle.yml


# clean handlers
- name: Clean anchors/
  listen: Reset CA bundle
  include_tasks: ./clean_anchors.yml

- name: Revert CA bundle
  listen: Reset CA bundle
  include_tasks: ./revert_bundle.yml
  loop: "{{ target_cabundles }}"

